model_path: /content/drive/MyDrive/MLSP Paper/Experimentation/resnet50_bs32_lr0.01_supcon_head_type_linear_warmup50/checkpoints/resnet50_bs32_lr0.01_supcon_ep9_loss2.9482.pt
log_dir: /content/drive/MyDrive/MLSP Paper/Evaluation
model_name: resnet50
head_type: linear
feature_dim: 128
use_projection: true
data_root: /content/DeepFakeArt
vit_mode: cls+gap

train_similar_json: data/train_similar.json
train_dissimilar_json: data/train_dissimilar.json
test_similar_json: data/test_similar.json
test_dissimilar_json: data/test_dissimilar.json

device: cuda
