model_path: /content/drive/MyDrive/MLSP Paper/Experimentation/resnet50_bs128_lr0.01_supcon_head_type_linear_warmupDynamic/checkpoints/resnet50_bs128_lr0.01_supcon_ep16_loss3.5363.pt
log_dir: /content/drive/MyDrive/MLSP Paper/Evaluation
model_name: dfa_con_rn
head_type: linear
feature_dim: 128
use_projection: false
data_root: /content/DeepFakeArt
vit_mode: cls+gap
eval_batch_size: 256

train_similar_json: /content/DeepFakeArt/similar/train_similar.json
train_dissimilar_json: /content/DeepFakeArt/dissimilar/train_dissimilar.json
test_similar_json: /content/DeepFakeArt/similar/test_similar.json
test_dissimilar_json: /content/DeepFakeArt/dissimilar/test_dissimilar.json

device: cuda
